POST {{host}}/api/v1/chat/kakao?client_name=solar
accept: application/json
Content-Type: application/json

{
  "intent": {
    "id": "es2mb937ado5bmj04dkzmogn",
    "name": "블록 이름"
  },
  "userRequest": {
    "timezone": "Asia/Seoul",
    "params": {
      "ignoreMe": "true"
    },
    "block": {
      "id": "es2mb937ado5bmj04dkzmogn",
      "name": "블록 이름"
    },
    "utterance": "동카름 주변 맛집 추천해줘",
    "lang": null,
    "user": {
      "id": "945412",
      "type": "accountId",
      "properties": {}
    }
  },
  "bot": {
    "id": "your_bot_id",
    "name": "봇 이름"
  },
  "action": {
    "name": "your_action_name",
    "clientExtra": null,
    "params": {},
    "id": "your_action_id",
    "detailParams": {}
  }
}
