POST {{host}}/api/v1/embeddings/passage?client_name=solar
accept: application/json
Content-Type: application/json

{
  "messages": [
    "제주도는 흑돼지, 갈치조림, 전복죽이 유명하고 정말 맛있어"
  ],
  "model": "solar-embedding-1-large-passage",
  "id": "test"
}